# Generated by Django 2.2.25 on 2021-12-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211216_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
