# Generated by Django 3.2.9 on 2021-12-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_perfil_img_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
    ]
