# Generated by Django 3.2.9 on 2021-12-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_perfil_img_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='img_perfil',
            field=models.ImageField(default='default.png', upload_to='media/user/'),
        ),
    ]
