# Generated by Django 3.2.9 on 2021-12-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='usuario',
            new_name='user',
        ),
    ]
