# Generated by Django 3.2.9 on 2021-12-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_alter_comentario_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(max_length=300),
        ),
    ]
